env:
  browser: true
  es6: true
  jquery: true
extends: 
  - 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
globals:
  $setTimeout: true
  $random: true
  $regex: true
  rb: true
  renderRbcomp: true
  React: true
  ReactDOM: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
