name: Gitee repos mirror

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Hub Mirror Action.
      uses: Yikun/hub-mirror-action@v0.07
      with:
        src: github/getrebuild
        dst: gitee/getrebuild
        dst_key: ${{ secrets.GITEE_PRIVATEKEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        white_list: "rebuild,rebuild-datas"